package main.java.quemepongo2.model;
// Generated 05-dic-2019 11:36:49 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "Ciudad", schema = "dbo", catalog = "QueMePongo2")
public class Ciudad implements java.io.Serializable {

	private int id;
	private String nombre;
	private String pais;
	private BigDecimal longitud;
	private BigDecimal latitud;
	private Set<CiudadUsuario> ciudadUsuarios = new HashSet<CiudadUsuario>(0);
	private Set<ReporteDelClima> reporteDelClimas = new HashSet<ReporteDelClima>(0);

	public Ciudad() {
	}

	public Ciudad(int id, String nombre, String pais) {
		this.id = id;
		this.nombre = nombre;
		this.pais = pais;
	}

	public Ciudad(int id, String nombre, String pais, BigDecimal longitud, BigDecimal latitud,
			Set<CiudadUsuario> ciudadUsuarios, Set<ReporteDelClima> reporteDelClimas) {
		this.id = id;
		this.nombre = nombre;
		this.pais = pais;
		this.longitud = longitud;
		this.latitud = latitud;
		this.ciudadUsuarios = ciudadUsuarios;
		this.reporteDelClimas = reporteDelClimas;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Pais", nullable = false)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "Longitud", precision = 9, scale = 6)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Column(name = "Latitud", precision = 9, scale = 6)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<CiudadUsuario> getCiudadUsuarios() {
		return this.ciudadUsuarios;
	}

	public void setCiudadUsuarios(Set<CiudadUsuario> ciudadUsuarios) {
		this.ciudadUsuarios = ciudadUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<ReporteDelClima> getReporteDelClimas() {
		return this.reporteDelClimas;
	}

	public void setReporteDelClimas(Set<ReporteDelClima> reporteDelClimas) {
		this.reporteDelClimas = reporteDelClimas;
	}

}
