package main.java.quemepongo2.model;
// Generated 16-oct-2019 12:54:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "Ciudad", schema = "dbo", catalog = "QueMePongo2")
public class Ciudad implements java.io.Serializable {

	private int id;
	private String nombre;
	private String pais;
	private Double longitud;
	private Double latitud;

	public Ciudad() {
	}

	public Ciudad(int id, String nombre, String pais) {
		this.id = id;
		this.nombre = nombre;
		this.pais = pais;
	}

	public Ciudad(int id, String nombre, String pais, Double longitud, Double latitud) {
		this.id = id;
		this.nombre = nombre;
		this.pais = pais;
		this.longitud = longitud;
		this.latitud = latitud;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Pais", nullable = false)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "Longitud", precision = 53, scale = 0)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "Latitud", precision = 53, scale = 0)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

}
