package main.java.quemepongo2.model;
// Generated 03-dic-2019 15:44:16 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CiudadUsuarioId generated by hbm2java
 */
@Embeddable
public class CiudadUsuarioId implements java.io.Serializable {

	private int ciudadId;
	private int usuarioId;

	public CiudadUsuarioId() {
	}

	public CiudadUsuarioId(int ciudadId, int usuarioId) {
		this.ciudadId = ciudadId;
		this.usuarioId = usuarioId;
	}

	@Column(name = "CiudadId", nullable = false)
	public int getCiudadId() {
		return this.ciudadId;
	}

	public void setCiudadId(int ciudadId) {
		this.ciudadId = ciudadId;
	}

	@Column(name = "UsuarioId", nullable = false)
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CiudadUsuarioId))
			return false;
		CiudadUsuarioId castOther = (CiudadUsuarioId) other;

		return (this.getCiudadId() == castOther.getCiudadId()) && (this.getUsuarioId() == castOther.getUsuarioId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCiudadId();
		result = 37 * result + this.getUsuarioId();
		return result;
	}

}
