package main.java.quemepongo2.model;
// Generated 03-dic-2019 15:44:16 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CiudadUsuario generated by hbm2java
 */
@Entity
@Table(name = "CiudadUsuario", schema = "dbo", catalog = "QueMePongo2")
public class CiudadUsuario implements java.io.Serializable {

	private CiudadUsuarioId id;
	private Ciudad ciudad;
	private Usuario usuario;
	private Integer indiceOrdenado;

	public CiudadUsuario() {
	}

	public CiudadUsuario(CiudadUsuarioId id, Ciudad ciudad, Usuario usuario) {
		this.id = id;
		this.ciudad = ciudad;
		this.usuario = usuario;
	}

	public CiudadUsuario(CiudadUsuarioId id, Ciudad ciudad, Usuario usuario, Integer indiceOrdenado) {
		this.id = id;
		this.ciudad = ciudad;
		this.usuario = usuario;
		this.indiceOrdenado = indiceOrdenado;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ciudadId", column = @Column(name = "CiudadId", nullable = false)),
			@AttributeOverride(name = "usuarioId", column = @Column(name = "UsuarioId", nullable = false)) })
	public CiudadUsuarioId getId() {
		return this.id;
	}

	public void setId(CiudadUsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CiudadId", nullable = false, insertable = false, updatable = false)
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UsuarioId", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "IndiceOrdenado")
	public Integer getIndiceOrdenado() {
		return this.indiceOrdenado;
	}

	public void setIndiceOrdenado(Integer indiceOrdenado) {
		this.indiceOrdenado = indiceOrdenado;
	}

}
