package main.java.quemepongo2.model;
// Generated 24-oct-2019 23:31:54 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReporteDelClima generated by hbm2java
 */
@Entity
@Table(name = "ReporteDelClima", schema = "dbo", catalog = "QueMePongo2")
public class ReporteDelClima implements java.io.Serializable {

	private Integer id;
	private Ciudad ciudad;
	private BigDecimal temperaturaActual;

	public ReporteDelClima() {
	}

	public ReporteDelClima(Ciudad ciudad, BigDecimal temperaturaActual) {
		this.ciudad = ciudad;
		this.temperaturaActual = temperaturaActual;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CiudadId", nullable = false)
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "TemperaturaActual", nullable = false, precision = 3)
	public BigDecimal getTemperaturaActual() {
		return this.temperaturaActual;
	}

	public void setTemperaturaActual(BigDecimal temperaturaActual) {
		this.temperaturaActual = temperaturaActual;
	}

}
