package main.java.quemepongo2.model;
// Generated 03-dic-2019 15:44:16 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario", schema = "dbo", catalog = "QueMePongo2", uniqueConstraints = @UniqueConstraint(columnNames = "Usuario"))
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String clave;
	private String usuario;
	private int genero;
	private boolean tieneBufanda;
	private boolean tieneLentes;
	private boolean tieneParaguas;
	private boolean tieneProtectorSolar;
	private boolean tieneGorra;
	private Set<CiudadUsuario> ciudadUsuarios = new HashSet<CiudadUsuario>(0);

	public Usuario() {
	}

	public Usuario(String clave, String usuario, int genero, boolean tieneBufanda, boolean tieneLentes,
			boolean tieneParaguas, boolean tieneProtectorSolar, boolean tieneGorra) {
		this.clave = clave;
		this.usuario = usuario;
		this.genero = genero;
		this.tieneBufanda = tieneBufanda;
		this.tieneLentes = tieneLentes;
		this.tieneParaguas = tieneParaguas;
		this.tieneProtectorSolar = tieneProtectorSolar;
		this.tieneGorra = tieneGorra;
	}

	public Usuario(String clave, String usuario, int genero, boolean tieneBufanda, boolean tieneLentes,
			boolean tieneParaguas, boolean tieneProtectorSolar, boolean tieneGorra, Set<CiudadUsuario> ciudadUsuarios) {
		this.clave = clave;
		this.usuario = usuario;
		this.genero = genero;
		this.tieneBufanda = tieneBufanda;
		this.tieneLentes = tieneLentes;
		this.tieneParaguas = tieneParaguas;
		this.tieneProtectorSolar = tieneProtectorSolar;
		this.tieneGorra = tieneGorra;
		this.ciudadUsuarios = ciudadUsuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Clave", nullable = false)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "Usuario", unique = true, nullable = false)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Genero", nullable = false)
	public int getGenero() {
		return this.genero;
	}

	public void setGenero(int genero) {
		this.genero = genero;
	}

	@Column(name = "TieneBufanda", nullable = false)
	public boolean isTieneBufanda() {
		return this.tieneBufanda;
	}

	public void setTieneBufanda(boolean tieneBufanda) {
		this.tieneBufanda = tieneBufanda;
	}

	@Column(name = "TieneLentes", nullable = false)
	public boolean isTieneLentes() {
		return this.tieneLentes;
	}

	public void setTieneLentes(boolean tieneLentes) {
		this.tieneLentes = tieneLentes;
	}

	@Column(name = "TieneParaguas", nullable = false)
	public boolean isTieneParaguas() {
		return this.tieneParaguas;
	}

	public void setTieneParaguas(boolean tieneParaguas) {
		this.tieneParaguas = tieneParaguas;
	}

	@Column(name = "TieneProtectorSolar", nullable = false)
	public boolean isTieneProtectorSolar() {
		return this.tieneProtectorSolar;
	}

	public void setTieneProtectorSolar(boolean tieneProtectorSolar) {
		this.tieneProtectorSolar = tieneProtectorSolar;
	}

	@Column(name = "TieneGorra", nullable = false)
	public boolean isTieneGorra() {
		return this.tieneGorra;
	}

	public void setTieneGorra(boolean tieneGorra) {
		this.tieneGorra = tieneGorra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<CiudadUsuario> getCiudadUsuarios() {
		return this.ciudadUsuarios;
	}

	public void setCiudadUsuarios(Set<CiudadUsuario> ciudadUsuarios) {
		this.ciudadUsuarios = ciudadUsuarios;
	}

}
