package main.java.quemepongo2.model;
// Generated 16-oct-2019 12:54:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario", schema = "dbo", catalog = "QueMePongo2")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String clave;
	private String usuario;
	private Double latitud;
	private Double longitud;
	private Set<Preferencias> preferenciases = new HashSet<Preferencias>(0);

	public Usuario() {
	}

	public Usuario(String clave, String usuario) {
		this.clave = clave;
		this.usuario = usuario;
	}

	public Usuario(String clave, String usuario, Double latitud, Double longitud, Set<Preferencias> preferenciases) {
		this.clave = clave;
		this.usuario = usuario;
		this.latitud = latitud;
		this.longitud = longitud;
		this.preferenciases = preferenciases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Clave", nullable = false)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "Usuario", nullable = false)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Latitud", precision = 53, scale = 0)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "Longitud", precision = 53, scale = 0)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Preferencias> getPreferenciases() {
		return this.preferenciases;
	}

	public void setPreferenciases(Set<Preferencias> preferenciases) {
		this.preferenciases = preferenciases;
	}

}
